### ISSUE TITLE
CT-HYB should check Eigen3 version

### ISSUE THREAD

**Issue by galexv** [ALPSCore/CT-HYB#6]
The code uses `determinant()` method on a permutation matrix, which was introduced only in [version 3.3](http://eigen.tuxfamily.org/index.php?title=3.3#Sparse_solvers). 

It would be good to insert required version at https://github.com/ALPSCore/CT-HYB/blob/master/CMakeLists.txt#L55 .

**Comment by shinaoka** [comment]
Hmm, the code uses determinant() method on a general matrix (Eigen::Matrix).
The code seems to compile with Eigen3.2.10.

**Comment by galexv** [comment]
I have not yet tried myself, but a user reports the following error (with [version 1.0.0](https://github.com/ALPSCore/CT-HYB/releases/tag/v1.0.0), but the corresponding code seems to not have changed since then):

>/home/soumen/soft/alps_core/CT-HYB-1.0.0/include/alps/fastupdate/./detail/util.hpp:208:54: error: ‘const PermutationQType’ has no member named ‘determinant’
         results[0] *= lu.permutationP().determinant()*lu.permutationQ().determinant();

The [corresponding code line](https://github.com/ALPSCore/CT-HYB/blob/master/include/alps/fastupdate/detail/util.hpp#L208) calls `determinant()` on the result of [`permutationP()`](https://eigen.tuxfamily.org/dox/classEigen_1_1FullPivLU.html#a76330c0871f65dcc3b3ef0d3764b5c89) which returns a `permutationPType` object which is a [permutation matrix](https://eigen.tuxfamily.org/dox/classEigen_1_1PermutationMatrix.html). In the latest version it does have method [`determinant()`](https://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html#a726af9d266a22257b0489c54a0b0d6b7) but it seems it was introduced only in [version 3.3](http://eigen.tuxfamily.org/index.php?title=3.3#Miscellaneous).

**Comment by shinaoka** [comment]
Thank you. I will introduce a version check.

**Comment by shinaoka** [comment]
I've introduced a version check (3.3 is required).
But it seems to be too strict. I will relax it to 3.2.8.

**Comment by shinaoka** [comment]
It's now done.
